export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";
export const POST_POSTS_REQUEST = "POST_POSTS_REQUEST";
export const POST_POSTS_SUCCESS = "POST_POSTS_SUCCESS";
export const POST_POSTS_FAILURE = "POST_POSTS_FAILURE";
